export type {
  Lawyer,
  NewLawyer,
  UpdateLawyer,
  LawyerResource,
  LawyerResult,
  LawyerCollection,
  LawyerInvite,
  NewLawyerInvite,
  LawyerInviteResult,
  LawyerInviteCollection,
  LawyerProfileDocument,
  NewLawyerProfileDocument,
  LawyerProfileDocumentResult,
  RejectLawyerRequest,
  UpdateInviteStatusRequest,
} from "@mah/api/src/clients/lawyers.api";
