import { useEffect, useMemo, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { useTranslation } from "react-i18next";
import type {
  ChatMessage,
  SendMessageRequest,
  Chat,
} from "@mah/api/src/clients/chat.api";
import type { MatterResult } from "@mah/api/src/clients/matters.api";
import type { ApiClientError } from "@mah/api/src/api/api.errors";
import { matterQueries } from "@mah/api/src/hooks/use-matters";
import { ActiveChatHeader } from "~/feature/chats/components/ChatHeader";
import { OpenMatterBanner } from "~/feature/chats/components/OpenMatterBanner";
import { ChatInput } from "~/feature/chats/components/chat-input";
import { MessageList } from "~/feature/chats/components/MessageList";
import { CitationsSidebar } from "~/feature/chats/components/CitationsSidebar";
import { DocumentIndicator } from "~/feature/chats/components/DocumentIndicator";
import { OpenMatterDialog } from "~/feature/matters/components/OpenMatterDialog";
import type { OpenMatterFormValues } from "~/feature/matters/components/OpenMatterDialog";
import { MatterPreparingSheet } from "~/feature/matters/components/MatterPreparingSheet";
import { isMatterPrepared } from "~/feature/matters/components/matter-utils";
import { PageDetailsLoading } from "@mah/ui/components/molecules/PageDetailsLoading";
import { PageDetailsError } from "@mah/ui/components/molecules/PageDetailsError";
import {
  isReplyAwaiting,
  useChatMutations,
} from "@mah/api/src/hooks/chats/use-chats";
import { useOpenMatter } from "@mah/api/src/hooks/use-matters";
import { useDocumentStatus } from "@mah/api/src/hooks/documents/use-documents";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router";
import { z } from "zod";
import type { AsyncState } from "@mah/api/src/api/api.types";

const sendMessageSchema = z.object({
  content: z.string().min(1, "Message cannot be empty"),
});
export type SendMessageForm = z.infer<typeof sendMessageSchema>;

interface ChatScreenProps extends AsyncState {
  chat: Chat;
  messages: ChatMessage[];
  messagesLoading: boolean;
}

const PREPARATION_POLL_INTERVAL_MS = 3000;

export const ChatScreen = ({
  chat,
  isLoading,
  error,
  messages,
  messagesLoading,
}: ChatScreenProps) => {
  const navigate = useNavigate();
  const { t } = useTranslation("chats");

  // Using the grouped mutations hook
  const {
    sendMessage: sendMessageMutation,
    deleteChat: deleteChatMutation,
    retryMessage: retryMessageMutation,
  } = useChatMutations();

  const [showConfirmDialog, setShowConfirmDialog] = useState(false);
  const [preparingMatterId, setPreparingMatterId] = useState<string | null>(
    null,
  );
  const [showPreparingSheet, setShowPreparingSheet] = useState(false);

  const openMatter = useOpenMatter({
    onOpenSuccess: ({ data }) => {
      setShowConfirmDialog(false);
      setPreparingMatterId(data.id);
      setShowPreparingSheet(true);
    },
  });

  // Poll the just-created matter until the summary job marks it ready.
  const {
    data: preparedMatter,
    isError: prepareError,
    refetch: retryPreparation,
  } = useQuery<MatterResult, ApiClientError>({
    ...matterQueries.detail(preparingMatterId ?? ""),
    enabled: !!preparingMatterId,
    refetchInterval: (query: { state: { data?: MatterResult } }) =>
      isMatterPrepared(query.state.data?.data?.attributes)
        ? false
        : PREPARATION_POLL_INTERVAL_MS,
  });

  const isPrepared = isMatterPrepared(preparedMatter?.data?.attributes);

  // Notify once when the matter transitions to ready, even if the sheet is closed.
  const readyToastShown = useRef(false);
  useEffect(() => {
    if (isPrepared && !readyToastShown.current) {
      readyToastShown.current = true;
      toast.success(t("openMatter.ready"));
    }
  }, [isPrepared, t]);

  const { data: userDocumentStatus } = useDocumentStatus(chat?.id ?? "");

  const {
    handleSubmit,
    setValue,
    watch,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<SendMessageForm>({
    resolver: zodResolver(sendMessageSchema),
    defaultValues: {
      content: "",
    },
  });

  const messageContent = watch("content");

  // Gather sources from the latest assistant message to show in the right sidebar
  const lastAssistantMessage = [...(messages || [])]
    .reverse()
    .find(
      (m) =>
        m.senderType === "assistant" ||
        !m.senderType ||
        m.metadata?.sources?.length,
    );
  const activeSources = lastAssistantMessage?.metadata?.sources || [];

  // Read-only AI summary preview shown in the confirm dialog (the real
  // summary is generated by the async job after the matter is opened).
  const summaryPreview = useMemo(() => {
    const assistant = [...(messages || [])]
      .reverse()
      .find((m) => m.senderType === "assistant");
    if (!assistant) return null;
    const text = assistant.content.trim().replace(/\s+/g, " ");
    return text.length > 320 ? `${text.slice(0, 320)}…` : text;
  }, [messages]);

  const hasEnoughContext = (messages?.length ?? 0) >= 2;

  const handleRenameChat = () => {
    const newTitle = window.prompt("Enter new chat title:", chat?.title || "");
    if (newTitle && newTitle.trim() && newTitle !== chat?.title) {
      // Handle rename logic if needed
    }
  };

  const handleDeleteChat = () => {
    if (!chat) return;
    deleteChatMutation.mutate(chat.id, {
      onSuccess: () => {
        navigate("/chats/recents");
      },
    });
  };

  const handleShareChat = () => {
    if (!chat) return;
    const shareUrl = `${window.location.origin}/chats/${chat.id}`;
    if (navigator.share) {
      navigator.share({
        title: chat.title || "Legal Consultation",
        text: "Check out this legal consultation",
        url: shareUrl,
      });
    } else {
      navigator.clipboard.writeText(shareUrl);
      alert("Chat link copied to clipboard!");
    }
  };

  const handleOpenMatter = () => {
    if (!chat) return;
    if (!hasEnoughContext) {
      toast(t("openMatter.tooShort"));
      return;
    }
    setShowConfirmDialog(true);
  };

  const handleConfirmOpenMatter = (values: OpenMatterFormValues) => {
    if (!chat) return;
    openMatter.mutate({
      clientUserId: chat.userId,
      sourceChatId: chat.id,
      title: values.title,
      summary: summaryPreview ?? undefined,
      jurisdiction: values.jurisdiction || undefined,
      practiceArea: values.practiceArea || undefined,
      isSharedWithLawyer: values.isSharedWithLawyer,
    });
  };

  const handleGoToMatter = () => {
    if (!preparingMatterId) return;
    setShowPreparingSheet(false);
    navigate(`/matters/${preparingMatterId}`);
  };

  const onSubmit = (data: SendMessageForm) => {
    if (!chat) return;
    const payload: SendMessageRequest = {
      chatId: chat.id,
      content: data.content,
      senderType: "user",
      userId: chat.userId,
    };

    sendMessageMutation.mutate(payload, {
      onSuccess: () => {
        reset();
      },
    });
  };

  const lastMessage = messages?.[messages.length - 1];
  const isReplyPending = lastMessage ? isReplyAwaiting(lastMessage) : false;
  const showTyping = sendMessageMutation.isPending || isReplyPending;

  // Citation focus state for sidebar highlighting
  const [focusedCitation, setFocusedCitation] = useState<number | null>(null);

  const handleCitationClick = (index: number) => {
    const el = document.getElementById(`citation-${index + 1}`);
    el?.scrollIntoView({ behavior: "smooth", block: "center" });
    setFocusedCitation(index);
    setTimeout(() => setFocusedCitation(null), 1500);
  };

  const citationMessageId = lastAssistantMessage?.id ?? undefined;

  if (isLoading)
    return (
      <PageDetailsLoading
        title="Loading Chat"
        description="Please wait while we load your conversation..."
      />
    );
  if (error)
    return (
      <PageDetailsError
        error="Failed to load chat"
        title="Error Loading Chat"
        description="We couldn't load your conversation. Please try again."
      />
    );
  if (!chat)
    return (
      <PageDetailsError
        error="Chat not found"
        title="Chat Not Found"
        description="The conversation you're looking for doesn't exist or has been removed."
      />
    );

  return (
    <div className="flex flex-1 min-h-0 w-full overflow-hidden bg-background">
      {/* Main Chat Area */}
      <div className="flex flex-col flex-1 min-h-0 border-r">
        <div className="flex-shrink-0 sticky top-0 z-10">
          <ActiveChatHeader
            title={chat.title!}
            onDeleteChat={handleDeleteChat}
            onRenameChat={handleRenameChat}
            onShareChat={handleShareChat}
            onOpenMatter={handleOpenMatter}
            isOpeningMatter={openMatter.isPending}
          />
        </div>

        <div className="flex-1 min-h-0 overflow-y-auto">
          <div className="mx-auto w-full max-w-4xl p-4 pb-8">
            {hasEnoughContext && (
              <OpenMatterBanner
                chatId={chat.id}
                onOpenAsMatter={handleOpenMatter}
              />
            )}
            <MessageList
              messages={messages || []}
              isLoading={messagesLoading}
              showTyping={showTyping}
              onRetry={(messageId) =>
                retryMessageMutation.mutate({ messageId, chatId: chat.id })
              }
              isRetrying={retryMessageMutation.isPending}
              citationMessageId={citationMessageId}
              onCitationClick={handleCitationClick}
            />
          </div>
        </div>

        <div className="flex-shrink-0 sticky bottom-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 border-t p-4">
          <div className="max-w-4xl mx-auto w-full">
            {userDocumentStatus?.hasDocument && (
              <DocumentIndicator
                filename={userDocumentStatus.filename}
                totalChunks={userDocumentStatus.totalChunks}
                sessionId={chat.id}
              />
            )}
            <form onSubmit={handleSubmit(onSubmit)}>
              <ChatInput
                value={messageContent || ""}
                onChange={(value) => setValue("content", value)}
                onSubmit={() => handleSubmit(onSubmit)()}
                sessionId={chat.id}
                placeholder="Ask a legal question or paste a clause to analyze..."
                isLoading={isSubmitting || sendMessageMutation.isPending}
                disabled={isSubmitting || sendMessageMutation.isPending}
              />
              {errors.content && (
                <p className="text-red-500 text-sm mt-2">
                  {errors.content.message}
                </p>
              )}
            </form>
          </div>
        </div>
      </div>

      {/* Right Sidebar for Source Citations */}
      <CitationsSidebar
        sources={activeSources}
        focusedCitation={focusedCitation}
      />

      {/* Open as Matter flow */}
      <OpenMatterDialog
        open={showConfirmDialog}
        onOpenChange={setShowConfirmDialog}
        defaultTitle={chat.title || ""}
        summaryPreview={summaryPreview}
        isSubmitting={openMatter.isPending}
        onSubmit={handleConfirmOpenMatter}
      />
      <MatterPreparingSheet
        open={showPreparingSheet}
        onOpenChange={setShowPreparingSheet}
        isReady={isPrepared}
        isError={prepareError && !isPrepared}
        onRetry={() => retryPreparation()}
        onGoToMatter={handleGoToMatter}
      />
    </div>
  );
};
