// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/legal-hub": {
    params: {};
  };
  "/legal-hub/:serviceId": {
    params: {
      "serviceId": string;
    };
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/chats/new": {
    params: {};
  };
  "/chats/recents": {
    params: {};
  };
  "/chats/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/documents": {
    params: {};
  };
  "/documents/:documentId": {
    params: {
      "documentId": string;
    };
  };
  "/lawyers": {
    params: {};
  };
  "/lawyers/:lawyerId": {
    params: {
      "lawyerId": string;
    };
  };
  "/users/:profile": {
    params: {
      "profile": string;
    };
  };
  "/users/settings": {
    params: {};
  };
  "/users/onboarding": {
    params: {};
  };
  "/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/app" | "/notifications" | "/contact" | "/legal-hub" | "/legal-hub/:serviceId" | "/login" | "/signup" | "/chats/new" | "/chats/recents" | "/chats/:chatId" | "/documents" | "/documents/:documentId" | "/lawyers" | "/lawyers/:lawyerId" | "/users/:profile" | "/users/settings" | "/users/onboarding" | "/help";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./feature/website/layouts/website.layout.tsx": {
    id: "feature/website/layouts/website.layout";
    page: "/about";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/app/index.tsx": {
    id: "routes/app/index";
    page: "/app";
  };
  "routes/notifications/index.tsx": {
    id: "routes/notifications/index";
    page: "/notifications";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/legal-hub.tsx": {
    id: "routes/legal-hub";
    page: "/legal-hub";
  };
  "routes/legal-hub/$serviceId.tsx": {
    id: "routes/legal-hub/$serviceId";
    page: "/legal-hub/:serviceId";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/signup";
  };
  "routes/chats/chats.new.tsx": {
    id: "routes/chats/chats.new";
    page: "/chats/new";
  };
  "routes/chats/chats.recents.tsx": {
    id: "routes/chats/chats.recents";
    page: "/chats/recents";
  };
  "routes/chats/$chatId.tsx": {
    id: "routes/chats/$chatId";
    page: "/chats/:chatId";
  };
  "routes/documents/index.tsx": {
    id: "routes/documents/index";
    page: "/documents";
  };
  "routes/documents/$documentId.tsx": {
    id: "routes/documents/$documentId";
    page: "/documents/:documentId";
  };
  "routes/lawyers/index.tsx": {
    id: "routes/lawyers/index";
    page: "/lawyers";
  };
  "routes/lawyers/$lawyerId.tsx": {
    id: "routes/lawyers/$lawyerId";
    page: "/lawyers/:lawyerId";
  };
  "routes/users/$profile.tsx": {
    id: "routes/users/$profile";
    page: "/users/:profile";
  };
  "routes/users/settings.tsx": {
    id: "routes/users/settings";
    page: "/users/settings";
  };
  "routes/users/onboarding.tsx": {
    id: "routes/users/onboarding";
    page: "/users/onboarding";
  };
  "routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "feature/website/layouts/website.layout": typeof import("./app/feature/www/layouts/website.layout.js");
  "routes/about": typeof import("./app/routes/www/about.js");
  "routes/app/index": typeof import("./app/routes/app/index.tsx");
  "routes/notifications/index": typeof import("./app/routes/notifications/index.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/legal-hub": typeof import("./app/routes/www/legal-hub.js");
  "routes/legal-hub/$serviceId": typeof import("./app/routes/legal-hub/$serviceId.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
  "routes/chats/chats.new": typeof import("./app/routes/chats/chats.new.tsx");
  "routes/chats/chats.recents": typeof import("./app/routes/chats/chats.recents.tsx");
  "routes/chats/$chatId": typeof import("./app/routes/chats/$chatId.tsx");
  "routes/documents/index": typeof import("./app/routes/documents/index.tsx");
  "routes/documents/$documentId": typeof import("./app/routes/documents/$documentId.tsx");
  "routes/lawyers/index": typeof import("./app/routes/lawyers/index.tsx");
  "routes/lawyers/$lawyerId": typeof import("./app/routes/lawyers/$lawyerId.tsx");
  "routes/users/$profile": typeof import("./app/routes/users/$profile.tsx");
  "routes/users/settings": typeof import("./app/routes/users/settings.tsx");
  "routes/users/onboarding": typeof import("./app/routes/users/onboarding.tsx");
  "routes/help": typeof import("./app/routes/help.tsx");
};