/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a new user
     * @description Creates a new user account with the provided credentials
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          headers: {
            "Set-Cookie"?: string;
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Bad request (e.g., invalid email format, weak password) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description User with this email already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate a user
     * @description Authenticates a user with email and password
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Authentication successful */
        200: {
          headers: {
            "Set-Cookie"?: string;
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthSuccessResponse"];
          };
        };
        /** @description Invalid request (missing fields, wrong format) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Invalid credentials */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user's chats
     * @description Returns a list of chats for the authenticated user
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of user's chats */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Chat"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new chat
     * @description Creates a new chat session
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateChatRequest"];
        };
      };
      responses: {
        /** @description Chat created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Chat"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chats/{chatId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get chat by ID
     * @description Returns a specific chat by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID of the chat to retrieve */
          chatId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Chat details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Chat"];
          };
        };
        /** @description Chat not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chats/{chatId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get chat messages
     * @description Retrieve messages for a specific chat
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID of the chat to get messages from */
          chatId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of messages in the chat */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Message"][];
          };
        };
        /** @description Chat not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * Send a message
     * @description Send a new message to a chat
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID of the chat to send message to */
          chatId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SendMessageRequest"];
        };
      };
      responses: {
        /** @description Message sent successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Message"];
          };
        };
        /** @description Invalid input or chat not found */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chats/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stream chat messages (SSE) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            messages: components["schemas"]["Message"][];
            /**
             * @description Optional model to use for the chat
             * @example gemma3:1b
             */
            model?: string;
          };
        };
      };
      responses: {
        /** @description Chat stream started */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all users
     * @description Returns a paginated list of users with filtering and sorting options
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of users to return per page */
          limit?: number;
          /** @description Page number for pagination */
          page?: number;
          /** @description Field to sort by */
          sortBy?: "createdAt" | "updatedAt" | "name" | "email";
          /** @description Sort order (asc or desc) */
          order?: "asc" | "desc";
          /** @description Search term to filter users by name or email */
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of users */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden - Admin access required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new user
     * @description Register a new user account. Can be used for both anonymous and registered users.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateUserRequest"];
        };
      };
      responses: {
        /** @description User created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Email already in use */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user by ID
     * @description Retrieve user details by user ID. Users can only view their own profile unless they are admins.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description User ID to retrieve */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Forbidden - Not authorized to view this user */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/lawyers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all lawyers
     * @description Returns a list of all registered lawyers with optional filtering
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number for pagination */
          page?: number;
          /** @description Number of items per page */
          limit?: number;
          /** @description Field to sort by */
          sortBy?: "createdAt" | "experience" | "rating" | "name";
          /** @description Sort order (ascending or descending) */
          sortOrder?: "asc" | "desc";
          /** @description Search term to filter lawyers by name or bio */
          search?: string;
          /** @description Filter lawyers by specialization */
          specialization?: string;
          /** @description Minimum years of experience */
          minExperience?: number;
          /** @description Maximum years of experience */
          maxExperience?: number;
          /** @description Minimum rating (0-5) */
          minRating?: number;
          /** @description Filter by location */
          location?: string;
          /** @description Filter by language spoken */
          language?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of lawyers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Lawyer"][];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new lawyer profile
     * @description Register a new lawyer in the system
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateLawyerRequest"];
        };
      };
      responses: {
        /** @description Lawyer created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Lawyer"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Lawyer with this email or bar number already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/lawyers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get lawyer by ID
     * @description Returns a single lawyer by their unique identifier
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lawyer's unique identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Lawyer details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Lawyer"];
          };
        };
        /** @description Lawyer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update lawyer profile
     * @description Update an existing lawyer's information
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Lawyer's unique identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateLawyerRequest"];
        };
      };
      responses: {
        /** @description Lawyer updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Lawyer"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Lawyer not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    User: {
      /**
       * Format: uuid
       * @description Unique identifier for the user
       */
      id?: string;
      /** @description Full name of the user */
      name?: string | null;
      /**
       * Format: email
       * @description User's email address
       */
      email?: string | null;
      /**
       * @description User's role in the system
       * @default user
       * @enum {string}
       */
      role: "user" | "admin" | "lawyer";
      /** @default true */
      isActive: boolean;
      /**
       * @description Whether the user is anonymous
       * @default false
       */
      isAnonymous: boolean;
      /** Format: date-time */
      lastLogin?: string | null;
      /**
       * Format: date-time
       * @description When the user was created
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description When the user was last updated
       */
      updatedAt?: string;
      /** @description Browser fingerprint for session management */
      fingerprint?: string;
      /** @description User agent string from the browser */
      userAgent?: string;
      /** @description User's age */
      age?: number;
      /**
       * @description User's gender
       * @enum {string}
       */
      gender?: "male" | "female" | "non_binary" | "prefer_not_to_say" | "other";
      /** @description User's country */
      country?: string;
      /** @description User's city */
      city?: string;
      /** @description User's phone number */
      phoneNumber?: string;
      /** @description User's occupation */
      occupation?: string;
      /** @description User's biography */
      bio?: string;
      /**
       * Format: uri
       * @description URL to user's profile picture
       */
      profilePicture?: string;
      /**
       * @description Whether the user has completed onboarding
       * @default false
       */
      isOnboarded: boolean;
    };
    RegisterRequest: {
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @description Must contain at least one uppercase, one lowercase, one number
       * @example SecurePass123
       */
      password: string;
      /**
       * @description User's full name
       * @example John Doe
       */
      name?: string;
    };
    LoginRequest: {
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email: string;
      /**
       * Format: password
       * @description User's password
       * @example SecurePass123
       */
      password: string;
    };
    AuthSuccessResponse: {
      /** @example true */
      success?: boolean;
      data?: {
        user?: components["schemas"]["User"];
        /** @description JWT access token */
        token?: string;
      };
    };
    ErrorResponse: {
      /**
       * @default false
       * @example false
       */
      success: boolean;
      error?: {
        /** @description Human-readable error message */
        message?: string;
        /**
         * @description Error code for programmatic handling
         * @example USER_EXISTS
         */
        code?: string | null;
      };
    };
    Chat: {
      /**
       * Format: uuid
       * @description Unique identifier for the chat
       */
      id?: string;
      /** @description Title of the chat */
      title?: string;
      /**
       * Format: uuid
       * @description ID of the user who owns the chat
       */
      userId?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Message: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      chatId?: string;
      /** @enum {string} */
      role?: "user" | "assistant" | "system";
      content?: string;
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt?: string;
    };
    CreateChatRequest: {
      /** @example Legal Consultation about Property */
      title: string;
    };
    SendMessageRequest: {
      /** @example What are my rights as a tenant? */
      content: string;
    };
    CreateUserRequest: {
      /**
       * @description User's full name
       * @example John Doe
       */
      name?: string;
      /**
       * Format: email
       * @description User's email address
       * @example user@example.com
       */
      email?: string;
      /**
       * @description User's password
       * @example securePassword123
       */
      password?: string;
      /**
       * @description User's role in the system
       * @default user
       * @example user
       * @enum {string}
       */
      role: "user" | "admin" | "lawyer";
      /** @description Browser fingerprint for session management */
      fingerprint?: string;
      /** @description User agent string from the browser */
      userAgent?: string;
    };
    Lawyer: {
      /**
       * Format: uuid
       * @description Unique identifier for the lawyer
       */
      id?: string;
      /**
       * Format: email
       * @description Lawyer's email address
       */
      email?: string;
      /** @description Full name of the lawyer */
      name?: string;
      /** @description Contact phone number */
      phone?: string;
      /** @description Legal specialization area */
      specialization?: string;
      /** @description Years of experience */
      experience?: number;
      /** @description Bar association registration number */
      barNumber?: string;
      /**
       * @description Whether the lawyer's credentials have been verified
       * @default false
       */
      isVerified: boolean;
      /** @description Languages spoken by the lawyer */
      languages?: string[];
      /** @description Professional biography */
      bio?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreateLawyerRequest: {
      /**
       * Format: email
       * @example lawyer@example.com
       */
      email: string;
      /** @example John Doe */
      name: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example Family Law */
      specialization?: string;
      /** @example 5 */
      experience?: number;
      /** @example BAR12345 */
      barNumber: string;
      /**
       * @example [
       *       "English",
       *       "French"
       *     ]
       */
      languages?: string[];
      /** @example Experienced family law attorney with 5+ years of practice */
      bio?: string;
    };
    UpdateLawyerRequest: {
      /** @example +1234567890 */
      phone?: string;
      /** @example Corporate Law */
      specialization?: string;
      /** @example 7 */
      experience?: number;
      /**
       * @example [
       *       "English",
       *       "French",
       *       "Spanish"
       *     ]
       */
      languages?: string[];
      /** @example Updated bio with more experience */
      bio?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
